Importing libraries

In [58]:
import pandas as pd
import numpy as np

Loading main dataset (city_day data)

In [59]:
# 
df = pd.read_csv(r"C:\Users\A.K\DATA_SCIENCE_WORKSPACE\kaggle_projects\project_1_air_quality\data\city_day.csv")

# View shape
print("Shape:", df.shape)

# Preview data
df.head()

Shape: (29531, 16)

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN

In [60]:
#Data quality check
print("Missing values:\n", df.isnull().sum())

Missing values:
 City              0
Date              0
PM2.5          4598
PM10          11140
NO             3582
NO2            3585
NOx            4185
NH3           10328
CO             2059
SO2            3854
O3             4022
Benzene        5623
Toluene        8041
Xylene        18109
AQI            4681
AQI_Bucket     4681
dtype: int64

In [61]:
#summary of dataset
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 29531 entries, 0 to 29530
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        29531 non-null  str
 1   Date        29531 non-null  str
 2   PM2.5       24933 non-null  float64
 3   PM10        18391 non-null  float64
 4   NO          25949 non-null  float64
 5   NO2         25946 non-null  float64
 6   NOx         25346 non-null  float64
 7   NH3         19203 non-null  float64
 8   CO          27472 non-null  float64
 9   SO2         25677 non-null  float64
 10  O3          25509 non-null  float64
 11  Benzene     23908 non-null  float64
 12  Toluene     21490 non-null  float64
 13  Xylene      11422 non-null  float64
 14  AQI         24850 non-null  float64
 15  AQI_Bucket  24850 non-null  str
dtypes: float64(13), str(3)
memory usage: 3.6 MB
None

In [62]:
# Keeping only useful columns for analysis
df_clean = df[[
    "City", "Date",
    "PM2.5", "PM10",
    "NO2", "CO", "SO2", "O3",
    "AQI", "AQI_Bucket"
]]
df_clean.head()

,City,Date,PM2.5,PM10,NO2,CO,SO2,O3,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,18.22,0.92,27.64,133.36,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,15.69,0.97,24.55,34.06,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,19.30,17.40,29.07,30.70,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,18.48,1.70,18.59,36.08,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,21.42,22.10,39.33,39.31,NaN,NaN

In [63]:
# Converting "Date" to datetime
df_clean["Date"] = pd.to_datetime(df_clean["Date"])
df_clean.dtypes

City                     str
Date          datetime64[us]
PM2.5                float64
PM10                 float64
NO2                  float64
CO                   float64
SO2                  float64
O3                   float64
AQI                  float64
AQI_Bucket               str
dtype: object

In [64]:
# Check missing values percentage
df_clean.isnull().mean() * 100

City           0.000000
Date           0.000000
PM2.5         15.570079
PM10          37.723071
NO2           12.139785
CO             6.972334
SO2           13.050692
O3            13.619586
AQI           15.851139
AQI_Bucket    15.851139
dtype: float64

In [65]:
#keep AQI rows
df_clean = df_clean.dropna(subset=["AQI"])
df_clean.head()

,City,Date,PM2.5,PM10,NO2,CO,SO2,O3,AQI,AQI_Bucket
28,Ahmedabad,2015-01-29,83.13,NaN,28.71,6.93,49.52,59.76,209.0,Poor
29,Ahmedabad,2015-01-30,79.84,NaN,28.68,13.85,48.49,97.07,328.0,Very Poor
30,Ahmedabad,2015-01-31,94.52,NaN,32.66,24.39,67.39,111.33,514.0,Severe
31,Ahmedabad,2015-02-01,135.99,NaN,42.08,43.48,75.23,102.70,782.0,Severe
32,Ahmedabad,2015-02-02,178.33,NaN,35.31,54.56,55.04,107.38,914.0,Severe

In [66]:
#handle pollutants missing values by filling with median
pollutants = ["PM2.5", "PM10", "NO2", "CO", "SO2", "O3"]

for col in pollutants:
    df_clean[col] = df_clean[col].fillna(df_clean[col].median())

In [67]:
#Sorting by time
df_clean = df_clean.sort_values(by=["City", "Date"])

In [68]:
#final check
df_clean.isnull().sum()

City          0
Date          0
PM2.5         0
PM10          0
NO2           0
CO            0
SO2           0
O3            0
AQI           0
AQI_Bucket    0
dtype: int64

In [69]:
#the clean dataset is ready for analysis and modeling
df.head()

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN

In [70]:
#This saves your cleaned dataset
df_clean.to_csv("../data/cleaned_air_quality.csv", index=False)